### ISSUE TITLE
MapService doesn't catch potential exceptions when LoadREgionsInBackground is called.

### ISSUE THREAD

**Issue by dlamkins** [agaertner/bhm-music-engine#1]
https://github.com/agaertner/bhm-music-engine/blob/529913b01bd2406f93f62a023c1d7a9b37a7e1e3/src/Core/Services/MapService.cs#L94-L183

This doesn't seem to catch an all exceptions.  Notably, `Gw2Sharp.WebApi.Exceptions.TooManyRequestsException`.

Probably `Exception` should be at least caught to avoid fatal crashes.  We're seeing some users crash from this.

**Comment by agaertner** [comment]
> https://github.com/agaertner/bhm-music-engine/blob/529913b01bd2406f93f62a023c1d7a9b37a7e1e3/src/Core/Services/MapService.cs#L94-L183
> 
> This doesn't seem to catch an all exceptions. Notably, `Gw2Sharp.WebApi.Exceptions.TooManyRequestsException`.
> 
> Probably `Exception` should be at least caught to avoid fatal crashes. We're seeing some users crash from this.

Thanks. Will be fixed. I should store this static data on disk as well.

**Comment by agaertner** [comment]
Fixed with #5
